#!/bin/zsh

# run all installation scripts

echo "Dotfiles:install"

set -e

cd "$(dirname $0)/.."

git submodule update --init --recursive

find . -maxdepth 2 -name install.sh | while read installer; do
  echo "Install ${installer}"
  zsh -c "${installer}"
done
