#!/bin/zsh

# run all installation scripts

echo "Dotfiles:install"

set -e

cd "$(dirname $0)/.."

git submodule update --init --recursive

find . -name install.sh | while read installer; do
  zsh -c "${installer}"
done
