#!/usr/bin/env bash

# update dotfiles cautiously (without symlinking)

cd "$(dirname $0)/.."

echo "Updating dotfiles..."
git pull
git submodule foreach git pull

# update homebrew

if [ "$(uname -s)" == "Darwin" ] && [ ! $(which brew) ]; then
    echo "Updating homebrew..."
    brew update
fi

