#!/usr/bin/env bash

# update dotfiles cautiously (without symlinking)

cd "$(dirname $0)/.."

echo "Updating dotfiles..."
git pull --rebase
git submodule foreach git pull --recurse-submodules --rebase origin master

# update homebrew
if [ "$(uname -s)" == "Darwin" ] && [ ! $(which brew) ]; then
    echo "Updating homebrew..."
    brew update
fi

